# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJLnomeMzLjOTiXFm7qRQ1Bse-60hUQq
"""

# --- 1. Preparación del Entorno ---
# Instalar las librerías necesarias
# transformers para trabajar con modelos de lenguaje de Hugging Face
# datasets para manejar colecciones de datos fácilmente
print("Asegúrate de tener instaladas las librerías: transformers, scikit-learn, datasets, pandas.")
print("Librerías instaladas.")

# Verificar si estamos usando una GPU (recomendado para el entrenamiento)

# Suprimir warnings de PyTorch y transformers
import warnings
warnings.filterwarnings("ignore")
import os
os.environ["TRANSFORMERS_NO_ADVISORY_WARNINGS"] = "1"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

import torch
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"Usando GPU: {torch.cuda.get_device_name(0)}")
else:
    device = torch.device("cpu")
    print("No se encontró GPU, usando CPU. El entrenamiento será más lento.")

print("\n--- 2. Carga y Preparación del Dataset Divertido: Clasificación de Emojis ---")

# Definir un dataset muy pequeño y divertido de frases y sus emojis
# Esto simula un escenario donde tenemos datos específicos y limitados
data = {
    "text": [
        "Me siento muy feliz hoy!",
        "Estoy bastante triste por las noticias.",
        "Esto es increíble! Me encanta!",
        "Qué día tan aburrido...",
        "Estoy emocionado por el bootcamp!",
        "No me gusta nada esto.",
        "Esto es una maravilla",
        "Me quiero ir a dormir",
        "Gracias por tu ayuda",
        "Que bien",
        "Lo siento mucho"
    ],
    "label": [
        "😊",  # Feliz
        "😔",  # Triste
        "🤩",  # Asombro/Admiración
        "😐",  # Aburrido/Neutral
        "🥳",  # Fiesta/Emoción
        "😠",  # Enfadado
        "🤩",
        "😴",
        "🙏",
        "😊",
        "😔"
    ]
}

# Mapear los emojis a IDs numéricos para que el modelo los entienda
# Y viceversa para poder interpretar las predicciones
unique_labels = list(set(data["label"]))
label_to_id = {label: i for i, label in enumerate(unique_labels)}
id_to_label = {i: label for i, label in enumerate(unique_labels)}

print(f"Emojis únicos detectados: {unique_labels}")
print(f"Mapeo de etiquetas a IDs: {label_to_id}")

# Convertir el dataset a un formato compatible con la librería datasets de Hugging Face
from datasets import Dataset, Features, Value, ClassLabel
import pandas as pd

df = pd.DataFrame(data)
df['label_id'] = df['label'].map(label_to_id)

# Definir las características del dataset, incluyendo las etiquetas como ClassLabel
features = Features({
    'text': Value(dtype='string'),
    'label': Value(dtype='string'), # Mantener la columna original si es necesario para referencia
    'label_id': ClassLabel(names=unique_labels)
})

dataset = Dataset.from_pandas(df, features=features)

print("\nDataset original (primeras filas):")
print(dataset.to_pandas().head())

# Cargar el tokenizador de DistilBERT
# El tokenizador convierte el texto en IDs numéricos que el modelo puede procesar
from transformers import AutoTokenizer
model_name = "distilbert-base-uncased" # Un SLM popular, más pequeño que BERT

print(f"\nCargando tokenizador para el modelo: {model_name}...")
tokenizer = AutoTokenizer.from_pretrained(model_name)
print("Tokenizador cargado.")

# Función para tokenizar el dataset
def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=50) # max_length para eficiencia

tokenized_dataset = dataset.map(tokenize_function, batched=True)

# Dividir el dataset en conjuntos de entrenamiento y validación
# Usamos un 80% para entrenar y un 20% para validar el modelo
print("\nDividiendo el dataset en entrenamiento y validación (80/20)...")
train_test_split = tokenized_dataset.train_test_split(test_size=0.2, seed=42) # Usamos una semilla para reproducibilidad
train_dataset = train_test_split["train"]
eval_dataset = train_test_split["test"]

print(f"Tamaño del dataset de entrenamiento: {len(train_dataset)} ejemplos")
print(f"Tamaño del dataset de validación: {len(eval_dataset)} ejemplos")

# Preparar el formato para el entrenamiento
train_dataset = train_dataset.remove_columns(["text", "label"]) # Eliminamos las columnas de texto y emoji original
eval_dataset = eval_dataset.remove_columns(["text", "label"])
train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label_id"])
eval_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label_id"])

# Renombrar la columna de etiquetas para que sea 'labels' (requerido por el Trainer de Hugging Face)
train_dataset = train_dataset.rename_column("label_id", "labels")
eval_dataset = eval_dataset.rename_column("label_id", "labels")

print("\n--- 3. Carga del Modelo SLM (DistilBERT) ---")

# Cargar el modelo DistilBERT pre-entrenado para clasificación de secuencias
# num_labels es el número de clases (emojis) que queremos clasificar
from transformers import AutoModelForSequenceClassification

print(f"Cargando el modelo pre-entrenado: {model_name} para {len(unique_labels)} etiquetas...")
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(unique_labels),
    id2label=id_to_label, # Para que el modelo sepa el nombre de cada label
    label2id=label_to_id # Y viceversa
).to(device) # Mover el modelo a la GPU si está disponible
print("Modelo cargado y configurado para clasificación.")

print("\n--- 4. Fine-tuning del SLM (¡Entrenamiento rápido!) ---")

# Importar las clases necesarias para el entrenamiento
from transformers import TrainingArguments, Trainer
from sklearn.metrics import accuracy_score
import numpy as np

# Función para calcular las métricas de evaluación (en este caso, la precisión)
def compute_metrics(p):
    predictions = np.argmax(p.predictions, axis=1)
    return {"accuracy": accuracy_score(p.label_ids, predictions)}

# Configurar los argumentos de entrenamiento
# Aquí definimos cómo se comportará el proceso de entrenamiento (épocas, tasa de aprendizaje, etc.)
training_args = TrainingArguments(
    output_dir="./results",                     # Directorio donde se guardarán los resultados
    eval_strategy="epoch",                # Evaluar después de cada época
    learning_rate=2e-5,                         # Tasa de aprendizaje
    per_device_train_batch_size=8,             # Tamaño del batch por dispositivo para entrenamiento
    per_device_eval_batch_size=8,              # Tamaño del batch por dispositivo para evaluación
    num_train_epochs=5,                         # Número de épocas de entrenamiento (ajustar según necesidad)
    weight_decay=0.01,                          # Regularización para evitar el sobreajuste
    logging_dir='./logs',                       # Directorio para los logs de TensorBoard
    logging_steps=10,
    report_to="none"                            # Deshabilitar reportes a W&B u otros
)

# Crear el objeto Trainer
# El Trainer se encarga de todo el bucle de entrenamiento, evaluación y guardado
trainer = Trainer(
    model=model,                                # El modelo a entrenar
    args=training_args,                         # Los argumentos de entrenamiento
    train_dataset=train_dataset,                # El dataset de entrenamiento
    eval_dataset=eval_dataset,                  # El dataset de validación
    tokenizer=tokenizer,                        # El tokenizador
    compute_metrics=compute_metrics             # La función para calcular métricas
)

print("\nComenzando el fine-tuning del modelo. ¡Esto será rápido!")
# ¡Entrenar el modelo!
trainer.train()
print("\nFine-tuning completado.")

print("\n--- 5. Evaluación y Predicciones ---")

# Evaluar el modelo en el conjunto de validación
print("\nEvaluando el modelo en el conjunto de validación...")
results = trainer.evaluate()
print(f"Resultados de la evaluación: {results}")

# Probar el modelo con nuevas frases (¡Momento interactivo!)
def predict_emoji(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding="max_length", max_length=50).to(device)
    with torch.no_grad():
        outputs = model(**inputs)
    logits = outputs.logits
    # Obtener la clase con la mayor probabilidad
    predicted_class_id = torch.argmax(logits, dim=1).item()
    # Convertir el ID de la clase de nuevo a su emoji
    predicted_emoji = id_to_label[predicted_class_id]
    return predicted_emoji

print("\n¡Hora de probar el modelo! Ingresa frases y el SLM intentará predecir el emoji.")
print("Escribe 'salir' para terminar.")

while True:
    user_input = input("\nIngresa una frase (o 'salir' para terminar): ")
    if user_input.lower() == 'salir':
        break
    predicted = predict_emoji(user_input)
    print(f"El SLM predice: {predicted}")

print("\n¡Gracias por probar el modelo de clasificación de emojis con un SLM!")